----
--	Author:         Joshua Donais                                         
--      Creation Date:  April 9. 2019                                           
--      Due Date:       April 18, 2019                                          
--      Course:         CSC310 010                                              
--      Professor:      Dr. Spiegel                                             
--      Assignment:     #3                                                      
--      Filename:       parse.adb                                                
--      Purpose:        This program will utilize the lexemes generated by the  
--                      program written in project 2 (lex) to parse a file and  
--                      determine if the program follows the grammar defined    
--                      in grammarWorksheet.pdf. If errors are encountered,
--                      as long as they are not fatal, the parser will document
--                      the error and try to recover. At the end of the parsing
--                      function, all errors and the quantity of erros will be
--                      reported.
--      Time Spent on                                                           
--      Project (h):                                                            
--      Design:         2                                                       
--      Programming:    0                                                        
--      Testing:        0                                                       
--      Debugging:      0                                                       
------------------------------------------------------------------------------
--TODO fix output of lex program to correctly identify ENDSYM
--TODO fix lex program to correctly identify what qualifies 
--      as an identifier or factor
--TODO fix lex program to correctly identify operators 
--      (or determine if you can leave it)

with text.io;    use text.io
with lex;

PROCEDURE parse is

--****************
--  Main Procedure
--****************
--Declarations
    progFile, outFile       :   file_type;

BEGIN
    put_line("Form: parse <progFile> <switch> <outFile>");
    if argument_count = 0; then
        openReadFile(progFile);

END parse;
